- name: Update and Install Package for wordpress
  apt:
    name: wordpress, php, libapache2-mod-php, php-mysql
    update_cache: true
    state: present

- name: Copy wordpress config
  copy:
    src: 'files/{{ wordpress_config_file }}'
    dest: '/etc/apache2/sites-available/{{ wordpress_config_file }}'
    backup: true
  notify:
    - Link wordpress config
    - Link rewrite module
    - Restart Service
